# Configurações globais da simulação

DT = 1  # tamanho do passo (1 ciclo = 1 dia/hora)
LARGURA_MAPA = 500
ALTURA_MAPA = 500

ENERGIA_INICIAL_COELHO = 30
ENERGIA_INICIAL_RAPOSA = 40
ENERGIA_INICIAL_PLANTA = 15

CUSTO_MOVIMENTO = 1
CUSTO_EXISTENCIA = 0.5

CICLOS_PARA_NOVA_PLANTA = 5
NUTRIENTES_MINIMOS = 10